

#declare -a arr=("CapabilityStatement" "StructureDefinition" "ImplementationGuide" "SearchParameter" "MessageDefinition" "OperationDefinition" "CompartmentDefinition" "StructureMap" "GraphDefinition" "ExampleScenario" "CodeSystem" "ValueSet" "ConceptMap" "NamingSystem" "TerminologyCapabilities" "Provenance" "AuditEvent" "Consent" "Composition" "DocumentManifest" "DocumentReference" "CatalogEntry" "Basic" "Binary" "Bundle" "Linkage" "MessageHeader" "OperationOutcome" "Parameters" "Subscription" "Patient" "Practitioner" "PractitionerRole" "RelatedPerson" "Person" "Group" "Organization" "OrganizationAffiliation" "HealthcareService" "Endpoint" "Location" "Substance" "BiologicallyDerivedProduct" "Device" "DeviceMetric" "Task" "Appointment" "AppointmentResponse" "Schedule" "Slot" "VerificationResult" "Encounter" "EpisodeOfCare" "Flag" "List" "Library" "AllergyIntolerance" "AdverseEvent" "ConditionProblem" "Procedure" "FamilyMemberHistory" "ClinicalImpression" "DetectedIssue" "Observation" "Media" "DiagnosticReport" "Specimen" "BodyStructure" "ImagingStudy" "QuestionnaireResponse" "MolecularSequence" "MedicationRequest" "MedicationAdministration" "MedicationDispense" "MedicationStatement" "Medication" "MedicationKnowledge" "Immunization" "ImmunizationEvaluation" "ImmunizationRecommendation" "CarePlan" "CareTeam" "Goal" "ServiceRequest" "NutritionOrder" "VisionPrescription" "RiskAssessment" "RequestGroup" "Communication" "CommunicationRequest" "DeviceRequest" "DeviceUseStatement" "GuidanceResponse" "SupplyRequest" "SupplyDelivery" "Coverage" "CoverageEligibilityRequest" "CoverageEligibilityResponse" "EnrollmentRequest" "EnrollmentResponse" "Claim" "ClaimResponse" "Invoice" "PaymentNotice" "PaymentReconciliation" "Account" "ChargeItem" "ChargeItemDefinition" "Contract" "ExplanationOfBenefit" "InsurancePlan" "ResearchStudy" "ResearchSubject" "ActivityDefinition" "DeviceDefinition" "EventDefinition" "ObservationDefinition" "PlanDefinition" "Questionnaire" "SpecimenDefinition" "ResearchDefinition" "ResearchElementDefinition" "Evidence" "EvidenceVariable" "EffectEvidenceSynthesis" "RiskEvidenceSynthesis" "Measure" "MeasureReport" "TestScript" "TestReport" "MedicinalProduct" "MedicinalProductAuthorization" "MedicinalProductContraindication" "MedicinalProductIndication" "MedicinalProductIngredient" "MedicinalProductInteraction" "MedicinalProductManufactured" "MedicinalProductPackaged" "MedicinalProductPharmaceutical" "MedicinalProductUndesirableEffect" "SubstancePolymer" "SubstanceReferenceInformation" "SubstanceSpecification")
declare -a arr=("SampledData" "Signature" "Age" "Distance" "Count" "Contributor" "DataRequirement" "RelatedArtifact" "UsageContext" "ParameterDefinition" "Expression" "TriggerDefinition")

for i in "${arr[@]}"; do
    curl "https://www.hl7.org/fhir/${i}.profile.json" > "${i}.json"
    echo "$i"
done
