name: Build and run tests

on:
  pull_request:
    branches: [ master ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Get openssl
        run: >
          sudo apt-get update &&
          sudo apt-get install curl git openssl -y
      - name: Add libssl.so to path
        run: echo $(ldconfig -p | grep libssl.so | awk -F' ' '{print $NF}') >> $GITHUB_PATH
      - name: Test via install
        uses: JJ/raku-test-action@main