name: Build and run tests

on:
  pull_request:
    branches: [ master ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Get libs
        run: >
          sudo apt-get update &&
          sudo apt-get install build-essential curl git libssl-dev openssl -y
      - name: install rakudo
        run: |
          mkdir ~/rakudo && cd $_
          curl -LJO https://rakudo.org/latest/star/src
          tar -xzf rakudo-star-*.tar.gz
          mv rakudo-star-*/* .
          rm -fr rakudo-star-*
          ./bin/rstar install
          echo "export PATH=$(pwd)/bin/:$(pwd)/share/perl6/site/bin:$(pwd)/share/perl6/vendor/bin:$(pwd)/share/perl6/core/bin:\$PATH" >> ~/.bashrc
      - name: Cache
        uses: actions/cache@v2
        with:
          path: ~/.raku/
          key: ${{ runner.os }}-${{ hashFiles('META6.json') }}
      - name: Run zef install .
        run: |
          source ~/.bashrc
          export OPENSSL_PREFIX=$(ldconfig -p | grep libssl.so | awk -F' ' '{print $NF}')
          zef install .