name: Build and run tests

on:
  pull_request:
    branches: [ master ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Get openssl
        run: >
          sudo apt-get update &&
          sudo apt-get install curl git openssl -y &&
          ln -s /lib/x86_64-linux-gnu/libssl.so.1.1 /lib/x86_64-linux-gnu/libssl.so
      - name: Test via install
        uses: JJ/raku-test-action@main