name: Build and run tests

on:
  pull_request:
    branches: [ master ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Get openssl
        run: >
          sudo apt-get update &&
          sudo apt-get install curl git openssl -y
      - name: Cache
        uses: actions/cache@v2
        with:
          path: ~/.raku/
          key: ${{ runner.os }}-${{ hashFiles('META6.json') }}
      - name: Run zef install .
        run: |
          export OPENSSL_PREFIX=$(ldconfig -p | grep libssl.so | awk -F' ' '{print $NF}')
          zef install .