name: Build and run tests

on:
  pull_request:
    branches: [ master ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Get openssl
        run: apt-get update && apt-get install openssl -y
      - name: Test via install
        uses: JJ/raku-test-action@main