name: Build and run tests

on:
  pull_request:
    branches: [ master ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Get libs
        run: >
          sudo apt-get update &&
          sudo apt-get install build-essential curl git libssl-dev openssl -y
      - name: Cache
        uses: actions/cache@v2
        with:
          path: /home/runner/.rakubrew/
          key: ${{ runner.os }}
      - name: install rakudo
        run: |
          (eval "$(/home/runner/.rakubrew/bin/rakubrew init Bash)" && zef --version) || (
            curl https://rakubrew.org/install-on-perl.sh | sh
            eval "$(/home/runner/.rakubrew/bin/rakubrew init Bash)"
            rakubrew build moar
            rakubrew build zef
          )
      - name: Cache
        uses: actions/cache@v2
        with:
          path: /home/runner/.raku/
          key: ${{ runner.os }}-${{ hashFiles('META6.json') }}
      - name: Run zef install .
        run: |
          eval "$(/home/runner/.rakubrew/bin/rakubrew init Bash)"
          zef install .